// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRB0W-YXnP2IWijrV61PD_t6jBDtFW3Qc',
    appId: '1:239110705161:web:71d527fa21b188d38428d8',
    messagingSenderId: '239110705161',
    projectId: 'mobilprojesi-56246',
    authDomain: 'mobilprojesi-56246.firebaseapp.com',
    storageBucket: 'mobilprojesi-56246.appspot.com',
    measurementId: 'G-XPXZS13RKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWvq7i9-qzSa2GJsiGQYQrgsLN_7o69vM',
    appId: '1:239110705161:android:068f38d597da2def8428d8',
    messagingSenderId: '239110705161',
    projectId: 'mobilprojesi-56246',
    storageBucket: 'mobilprojesi-56246.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDKQbX5wgtfzMPulIaqfSch1f7bafoGy8',
    appId: '1:239110705161:ios:03a6478b81380a9d8428d8',
    messagingSenderId: '239110705161',
    projectId: 'mobilprojesi-56246',
    storageBucket: 'mobilprojesi-56246.appspot.com',
    iosClientId: '239110705161-vp8vfmft3i2a3vcac9meb0qs05t7f6ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilProjesi',
  );
}
